### ISSUE TITLE
plugin.video.L0RE.dmax - also show series specials

### ISSUE THREAD

**Issue by retrofreak83** [kodinerds/repo#102]
This is a feature request.

There are some series that also have "specials" which are not part of the ordinary seasons.
I would appreciate if these were also integrated into the catalog.
For example, the series Steel Buddies has various specials which are listed here: https://www.dmax.de/programme/steel-buddies (see category "SPECIAL").

**Comment by mobsean** [comment]
![screenshot000](https://user-images.githubusercontent.com/32038980/60212127-c58ac880-9860-11e9-8454-66a5d3b4d66a.png)

Now looks like this. Depending on your sort settings.

**Comment by retrofreak83** [comment]
Great! Thanks!
