### ISSUE TITLE
plugin.video.L0RE.dmax - watched status in favourite folder

### ISSUE THREAD

**Issue by MeCias** [kodinerds/repo#104]
Hi,

I would appreciate if it could be possible to show the watched status in the dmax favourite folder as well. As soon all episodes are watched the folder of the show in the dmax favourite overview shows that too. That helps that as soon a new episode is available you do not have to go through all folder to check, you easily can see the status already in the favourites overview.

Thanks in advance.

**Comment by mobsean** [comment]
Hi,
just to get this straight. You are talking about this favorite folder? 
![screenshot000](https://user-images.githubusercontent.com/32038980/60370304-97d78800-99f6-11e9-80a6-8115e0ef920e.jpg)

_As soon all episodes are watched the folder of the show in the dmax favourite overview shows that too. _

Can you post a Screenshot with what you exactly mean with that? I dont see this "is watched" in the overview....

**Comment by MeCias** [comment]
Hi,

thank you for your response.

Yes I was talking about that folder. My issue is with the episode folders within the *My DMAX-Favorites* Folder.

![Untitled](https://user-images.githubusercontent.com/4476171/60371392-69a77780-99f9-11e9-8a50-69fbab4e6764.jpg)

You can see in my screenshot three episode folders, all episodes in Moonshiners and Combat Dealers are watched. All episodes in Steelbudies have been watched too, but after your update the special episodes are still unwatched. 
Unfortunately I can not see the watched status in that overview. To verify if there are still unwatched episodes I have to go into each folder to check. I agree that three episode folders are no problem to check quickly, but 10 episode folder might be already a pain.  

It would be nice if in that overview I could already see if unwatched episodes are within that folders. Like if there are unwatched episodes, that folder is displayed as it does now. if all episodes are watched the folder is replaced through a tick like shown in my adjusted screenshot.

![Untitled2](https://user-images.githubusercontent.com/4476171/60371938-26e69f00-99fb-11e9-8936-d06b620e1dda.jpg)

At least in my opinion it makes it way easier if a new episode was released to see that quickly without sifting through all folder.

Thanks in advance for considering.

**Comment by mobsean** [comment]
Hey,
I looked at it and I can´t implement what you are looking for. Sorry.

Maybe this is a good workaround for you?! 
Open Options and set kodi filters to unwatched.

![screenshot000](https://user-images.githubusercontent.com/32038980/60399104-274c7a80-9b60-11e9-8935-a0b1e57efaea.jpg)
![screenshot001](https://user-images.githubusercontent.com/32038980/60399106-2ca9c500-9b60-11e9-9bf0-bb277199c391.jpg)

**Comment by MeCias** [comment]
Hi,
thanks for looking into it. Pity that is not possible to implement, I will have a look into your workaround. I guess it will work fine.
