### ISSUE TITLE
[Feature Request] - Search in Spotitube

### ISSUE THREAD

**Issue by Rouzax** [kodinerds/repo#11]
Would it be possible to create a search feature in Spotitube, were you can search for a song and play a playlist that contains that song?
As it is now when I want to play a certain song I need to find a playlist that contains that song.
What I can find in the [Spotify API](https://developer.spotify.com/web-api/search-item/) is that it is not possible

```
What about searching for playlists that contain a certain track?
Unfortunately, this is not supported yet.
```

Also found a feature request for this https://community.spotify.com/t5/Live-Ideas/Search-for-Public-Playlists-that-Contain-Song-Artist/idi-p/144576

If finding  playlist is not possible than maybe on search and play that one song.

**Comment by tyl0re** [comment]
List the Playlist wouldn't be possible if they dont support it. Im Not Shure Search for the Song, is needet. 
Spotitube. Plays the Video From YouTube. An Search for an Video, would be the Same as the Youtube Search.
Mayby i Have misunderstood what you mean

**Comment by Rouzax** [comment]
Song search for me would be nice. Spotitube is great at finding the correct music video. I know that would also be possible directly from YouTube. 

The ultimate feature would be the playlist but as long as the API does not support it I understand that it would be impossible.

**Comment by Chico888** [comment]
I agree with Rouzax, search option in any way would be a great feature. I also wonder whether more options (search album, for instance..?) can be made available As I'm able to use the web player (play.spotify.com) as a free user without restrictions, most features would be available to grab? Would make this add-on even better.

**Comment by Collabsvito** [comment]
@Rouzax 
@Chico888 

Can this issue be marked as closed, because in the latest release a search function was integrated for spotify?

regards Collabsvito, the author of the latest Youtube Music Addon

**Comment by Rouzax** [comment]
Will give it a try. Thanks for that.

**Comment by Chico888** [comment]
Great feature, already noticed it. Thanks a ton Collabsvito!
