### ISSUE TITLE
My Recordings ar no longer shown

### ISSUE THREAD

**Issue by sgaechter** [kodinerds/repo#120]
instead, I can See some unknown recordings....

I already reinstalled the Plugin.

**Comment by patherren** [comment]
Same for me: I've different devices and it doesn't work on any device. 
Zattoo status is ok - Premium. Replay, EPG, Favorites etc. work, but in the recording section there are a lot of recordings, which don't belong to my account. 
When I check on the Zattoo App, everything is ok and I can see my own recordings.
