### ISSUE TITLE
Ran livestream without sound

### ISSUE THREAD

**Issue by maybeec** [kodinerds/repo#122]
With the latest Leia openelec build the sound of a livestream opened in the ran addon on kodi Stopps working after some seconds.

I restarted the system, downloaded the latest Leia test build of openelec, but nothing helps. Restarting the stream results in a working sound for again some seconds. Then the video shortly stops and afterwards continuous without sound. Video quality is good and fluent.

The livestream works on my laptop.

**Comment by hrickes** [comment]
fix for this issue

--- api.py.org  Thu Jan 17 12:29:30 2019
+++ api.py      Sat Aug 24 10:32:15 2019
@@ -169,6 +169,7 @@
         listitem = xbmcgui.ListItem(path=urld+"|"+userAgent)
         listitem.setProperty("inputstream.adaptive.license_type", "com.widevine.alpha")
         listitem.setProperty("inputstream.adaptive.manifest_type", "mpd")
+        listitem.setProperty('inputstream.adaptive.manifest_update_parameter', 'full')
         listitem.setProperty('inputstreamaddon', "inputstream.adaptive")
         xbmcplugin.setResolvedUrl(addon_handle, True, listitem)
         return ""

**Comment by hrickes** [comment]
fix for this issue

add the following line after line 171
listitem.setProperty("inputstream.adaptive.manifest_update_parameter", "full")

**Comment by Maven85** [comment]
i think the issue can be closed
