### ISSUE TITLE
Sky Go Plugin doesn't show Sky Sport Austria 2-4 in channel list

### ISSUE THREAD

**Issue by markus-schwarz** [kodinerds/repo#125]
The "Sky Sport Austria 2-4 (HD)" channels are available in the official iOS/Android/Windows app, but don't show up in the Kodi SkyGo Plugin. 

![image](https://user-images.githubusercontent.com/54775907/64093235-e2a7b000-cd57-11e9-9579-0507249f7cfe.png)

**Comment by wessm** [comment]
I have an issue related to this; since some time I can't watch individual matches of the Austrian Bundesliga (tipico Bundesliga) any more. The Individual matches are not listed in Live Planer and Livestreams, just the "Konferenz"

**Comment by Maven85** [comment]
Problem cannot be fixed because the API does not provide the necessary information
