### ISSUE TITLE
sporttotal addon plays live streams from the beginning

### ISSUE THREAD

**Issue by benedetto** [kodinerds/repo#134]
Since some weeks the sporttotal addon plays live streams not at the current (live) position but from the beginning of the stream. It is also not possible to fast-forward or skip to a more recent position. That means that when you start a live stream some time after its recording has started, you are forced to watch it time-shifted from the very beginning.

**Comment by benedetto** [comment]
Additional info: sometimes it helps to choose "Von hier starten" ("Start from here") from the context menu, but not reproducibly.

**Comment by benedetto** [comment]
@Collabsvito do you maybe have any idea?

**Comment by Collabsvito** [comment]
@benedetto 

Neue Version 1.0.4 ist online.
Die Livestreams können nicht gespult werden (sind nicht beeinflussbar und werden direkt von der Webseite bezogen).
