### ISSUE TITLE
joyn addon error

### ISSUE THREAD

**Issue by hemathor** [kodinerds/repo#136]
i just installed the joyn addon w/o any problems/errors (additional packages have been installed automatically), but when i try to start it, it fails.

the log says:
> 2019-11-17 12:06:25.843 T:1510974176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.HTTPError'>
>                                             Error Contents: HTTP Error 404: Not Found
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/plugin.video.joyn/default.py", line 3, in <module>
>                                                 from resources.lib import plugin
>                                               File "/home/osmc/.kodi/addons/plugin.video.joyn/resources/lib/plugin.py", line 999, in <module>
>                                                 libjoyn = lib_joyn(default_icon)
>                                               File "/home/osmc/.kodi/addons/plugin.video.joyn/resources/lib/lib_joyn.py", line 36, in __init__
>                                                 self.config = lib_joyn.get_config(default_icon)
>                                               File "/home/osmc/.kodi/addons/plugin.video.joyn/resources/lib/lib_joyn.py", line 653, in get_config
>                                                 ip_api_response = request_helper.get_json_response(url=CONST['IP_API_URL'].format(xbmc_helper.translation('LANG_CODE')), config=config, silent=True)
>                                               File "/home/osmc/.kodi/addons/plugin.video.joyn/resources/lib/request_helper.py", line 87, in get_json_response
>                                                 return loads(get_url(url, config, headers, params, post_data))
>                                               File "/home/osmc/.kodi/addons/plugin.video.joyn/resources/lib/request_helper.py", line 49, in get_url
>                                                 response = urlopen(request, timeout=40)
>                                               File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>                                                 return opener.open(url, data, timeout)
>                                               File "/usr/lib/python2.7/urllib2.py", line 435, in open
>                                                 response = meth(req, response)
>                                               File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>                                                 'http', request, response, code, msg, hdrs)
>                                               File "/usr/lib/python2.7/urllib2.py", line 473, in error
>                                                 return self._call_chain(*args)
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                                 result = func(*args)
>                                               File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>                                                 raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
>                                             HTTPError: HTTP Error 404: Not Found
>                                             -->End of Python script error report<--
> 2019-11-17 12:06:26.019 T:1519366880   ERROR: GetDirectory - Error getting plugin://plugin.video.joyn/
> 2019-11-17 12:06:26.020 T:1915221552   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.joyn/) failed

any advice would be much appreciated!

**Comment by Collabsvito** [comment]
@hemathor 

Ich nehme an Du hast einen VPN oder Adblocker in Betrieb, damit funktioniert das Addon leider nicht !
Siehe auch dazu: [https://www.kodinerds.net/index.php/Thread/66679-Pre-Release-Joyn-VOD-Live/?postID=554282#post554282](url) 
Bei weiteren Fragen bitte direkt in dem verlinkten Thread nachfragen, da der zuständige DEV hier nicht persönlich vertreten ist. MfG i.V.
