### ISSUE TITLE
Cannot install Netflix from this repository

### ISSUE THREAD

**Issue by Tokn59** [kodinerds/repo#143]
Hello, I have just istalled the Netflix Repository on the latest build (11/2019) of OSMC.

However when I go to the repository to install Netflix I get the following : 

Error : "Could not connect to repository"

Any idea what might be wrong ?

Many thanks for your help !!

Tony

**Comment by Collabsvito** [comment]
The netflix.repository is deprecated, please use this one: [https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.0.zip](url)
 Good Luck
