### ISSUE TITLE
Netflix repository

### ISSUE THREAD

**Issue by CastagnaIT** [kodinerds/repo#164]
Hi guys,
with the approval of asciidisco i am the current main maintainer of Netflix add-on 

I don't know who's in charge of this repository
I just wanted to let you know that as a result of some reports, I have been informed that you provide a Netflix repository no longer maintained

I'm not getting into your repository because i'm already too busy
but i would like to recommend one of these choices:
- Remove the no longer maintained Netflix repo provided
- Update the reference of the Netflix repository with my currently active

That would solve some of the "headaches" for the users,
Thanks

**Comment by Maven85** [comment]
Hi @CastagnaIT,
I have now removed the outdated repository and added yours.

Thanks
