### ISSUE TITLE
[plugin.video.sport1de] Potential Quickfix

### ISSUE THREAD

**Issue by sbroetz** [kodinerds/repo#170]
I was able to get the plugin running again by removing line 14 (i.e. the line that explicitly sets the "Host:" HTTP header to a fixed value) from resources/lib/client.py. At least I could access the livestreams again, did not dig very much deeper.

Background: Client.get_video_root() wants to make a request to https://www.sport1.de/...., so it does not make sense to set the Host: header hard-coded to "video.sport1.de". This simply does not match and the server will refuse to return something sensible in this setup.

Compare the output of

curl "https://www.sport1.de/api/navigations/video_navigation_root"

with

curl -H "Host: video.sport1.de" "https://www.sport1.de/api/navigations/video_navigation_root"

The first call gives a proper JSON result whereas the second one (with the "Host:" header set explicitly to a wrong) gives a PROTOCOL_ERROR.

**Comment by rolapp** [comment]
look at readme
