### ISSUE TITLE
Eurosport Player Kodi Addon 1.3.3 is broken

### ISSUE THREAD

**Issue by SimonD2107** [kodinerds/repo#19]
Hi there, the Kodi Eurosport Player addon v1.3.3 is broken. It won't bring up the listing at all when correctly using my Eurosport subscription logon details instead says I should check the log. I found a version of 1.3.1 on the web and had to go back to using that and turn off auto update so it wouldn't upgrade again.

A

**Comment by SimonD2107** [comment]
found the answer at the kodi forum http://forum.kodi.tv/showthread.php?tid=205551&page=5

**Comment by steisslinger** [comment]
Still not working for me on openelec / Kodi 16.1
Error:
File "/storage/.kodi/addons/plugin.video.eurosportplayer/resources/lib/channels.py", line 37, 
in thumb return image_base+self.image.replace(' ', '%20')
AttributeError: 'NoneType' object has no attribute 'replace'
Temp fix:
Comment out line 66:
    #   self.item['thumb'] = self.thumb()
Thumbs will not be updated but the player runs again.

**Comment by JinRonin** [comment]
Hi,
the update has been pushed to the repo.
http://forum.kodi.tv/showthread.php?tid=205551&pid=2546923
