### ISSUE TITLE
[spotitube] Playing the next song of a playlist does not work

### ISSUE THREAD

**Issue by soprano1203** [kodinerds/repo#21]
Playing a playlist with automatically does not work. The next song of the playlist must be selected always by hand from the list to listen to it. Sometimes it works after not reproduceable repeated start of the addon..

**Comment by SLiX69** [comment]
which addon you are referring to?

**Comment by soprano1203** [comment]
Oh, I see. Sorry..the spotitube (youtube music) addon

**Comment by Collabsvito** [comment]
@soprano1203 
I am the author of the latest [Youtube Music] Addon.
Please tell me more about your problems with this addon and which Kodiversion, System you use and other helpful Informations.
Tell me step by step what you trying to do and what are the failures that were generated !
If you are german, write your answer in german language, because I am german and my english is not so perfect, if not I will try to help in english.

**Comment by soprano1203** [comment]
Hey, sorry für die verspätete Nachricht. Ich verwende Libre Elec mit der Kodi Version 17.0-BETA6. Leider tritt das Problem sporadisch auf. Ich starte das Addon ganz normal, suche mir über Spotify eine beliebige Playlist raus, starte das erste Lied der Liste. Aus unerklärlichen Gründen ist es manchmal der Fall, dass die Playlist nicht automatisch der Reihe nach Lied für Lied abgespielt wird. Die Vor und Zurück Pfeile sind dann auch nicht verfügbar. Somit muss ich dann extra zurück zur Liste und manuell das nächste Lied auswählen. Auch ein Neustart des Addons bringt in dem Fall dann nichts. Und dann probiere ich es ein paar Tage später wieder und dann funktioniert es. Also leider nicht 100 Prozent reproduzierbar..

**Comment by Collabsvito** [comment]
@soprano1203 
Ich hatte schon gehofft, das Problem hätte sich erledigt:-)
Also wenn ich Dich richtig verstehe, öffnest Du eine Abspielliste (z.B: Toplisten > Top Dance Tunes >) in der Rubrik "Spotify", dort werden dann die einzelnen Titel mit Nummerierung angezeigt, Du machst einen -Rechtsklick- "ab hier abspielen" und möchtest das die Titel in der angezeigten Reihenfolge abgespielt werden, RICHTIG ???
Hast Du evtl. die Möglichkeit, es auf einem anderen System mit -KODI 17- zu testen, welchen Skin verwendest Du ?
Denn auf meinem System Win 8.1/64bit mit installiertem KODI-17.2 (Skin HorizonzV) läuft diese Funktion einwandfrei, es sei denn, das angezeigte Lied wird auf YOUTUBE nicht gefunden, dann wird das Darauffolgende abgespielt !
Oder es gibt die Möglichkeit: Die Abspielliste NICHT öffnen, -Rechtsklick- "+ ALLES + Abspielen +", dann wird auch jedes auf YOUTUBE verfügbare Lied der Abspielliste (in zufälliger Reihenfolge) abgespielt !

**Comment by tyl0re** [comment]
Schliesse es nachdem seit 5 May keine Antwort mehr kam
