### ISSUE TITLE
[plugin.video.filmstarts] def serienvideos() is missing

### ISSUE THREAD

**Issue by buhtz** [kodinerds/repo#23]
Please see line `853` where is a call to `serienvideos(url,page)`. But it is nowhere `def`ined.

Assign @tyl0re

**Comment by buhtz** [comment]
No response. No contribution.

**Comment by tyl0re** [comment]
Sorry, I have been in Holiday on August, an forgot it afterwards. Now its not Compatible to

**Comment by tyl0re** [comment]
Sorry, I have been in Holiday on August, an forgot it afterwards. Now its not Compatible to actual version
