### ISSUE TITLE
WDR plugin (0.8.7) doesn't play videos

### ISSUE THREAD

**Issue by zottelmann** [kodinerds/repo#31]
Kodi Log:

`ERROR: XFILE::CDirectory::GetDirectory - Error getting //wdradaptiv-vh.akamaihd.net/i/medp/ondemand/weltweit/fsk0/147/1473052/,1473052_16898983,1473052_16898984,1473052_16898986,1473052_16898985,.mp4.csmil/
16:16:09.621 T:1612   ERROR: Previous line repeats 1 times.
16:16:09.621 T:1612   ERROR: CVideoPlayer::OpenInputStream - error opening [//wdradaptiv-vh.akamaihd.net/i/medp/ondemand/weltweit/fsk0/147/1473052/,1473052_16898983,1473052_16898984,1473052_16898986,1473052_16898985,.mp4.csmil/master.m3u8]
16:16:09.621 T:1612  NOTICE: CVideoPlayer::OnExit()
16:16:09.622 T:4924   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.wdr/?url=http%3A%2F%2Fwww1.wdr.de%2Fmediathek%2Fvideo%2Fsendungen%2Fwdr-aktuell%2Fvideo-wdr-aktuell-780.html&mode=folge]
16:16:09.627 T:4924  NOTICE: CVideoPlayer::CloseFile()
16:16:09.627 T:4924  NOTICE: VideoPlayer: waiting for threads to exit
16:16:09.627 T:4924  NOTICE: VideoPlayer: finished waiting
16:16:09.627 T:4924  NOTICE: CVideoPlayer::CloseFile()
16:16:09.627 T:4924  NOTICE: VideoPlayer: waiting for threads to exit
16:16:09.627 T:4924  NOTICE: VideoPlayer: finished waiting
16:21:40.151 T:17288 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.wdr/?url=Live+Streams&mode=live
16:21:40.151 T:17288   ERROR: InputStream: Error opening, plugin://plugin.video.wdr/?url=Live+Streams&mode=live
16:21:43.350 T:4924   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
16:21:43.879 T:16812 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.wdr/?url=Live+Streams&mode=live
16:21:43.879 T:16812   ERROR: InputStream: Error opening, plugin://plugin.video.wdr/?url=Live+Streams&mode=live`

Any suggestions?

**Comment by tyl0re** [comment]
Took it offline since there is a working addon vfrom Sabre
