### ISSUE TITLE
plugin.video.disneychannel_de does not work anymore

### ISSUE THREAD

**Issue by NeroBurner** [kodinerds/repo#35]
disney has changed disneychannel.de to be forwarded to http://tv.disney.de

Also the extension http://disneychannel.de/_fta_stream/search.json?XXX is forwarded to http://tv.disney.de?XXX

So instead of the expected JSON response a html page is received and the whole plugin does not work anymore (except the livestream)

**Comment by tyl0re** [comment]
Since so mayn changes, i marked Disney Addon in Kodinerd Repo as Broken,
 and Made a new Disney Addon. It is now in the Repo

**Comment by NeroBurner** [comment]
thanks for the fast response, it's working again :)
