### ISSUE TITLE
Livetv url 

### ISSUE THREAD

**Issue by polojoe** [kodinerds/repo#36]
https://github.com/kodinerds/repo/blob/899f99e5b167f86063b16942408d4ff008b39f4a/plugin.video.servustv_com/default.py#L223

Bitte die Livetv Urls austauschen:
DE
https://liveservustv-i.akamaihd.net/hls/live/271000/ServusTV_DE/master_fbr2192.m3u8
AT
https://liveservustv-i.akamaihd.net/hls/live/270998/ServusTV_AT/master_fb1112.m3u8

**Comment by tyl0re** [comment]
Danke!
Neue Version ist Online
