### ISSUE TITLE
Falsche Pfade?

### ISSUE THREAD

**Issue by maciemesser** [kodinerds/repo#42]
Hi,

in

https://raw.githubusercontent.com/kodinerds/repo/master/addons.xml

finden sich wiederholt Pfade mit "addons", z.B 

<source>https://github.com/kodinerds/repo/tree/master/addons/plugin.audio.radioteddy_de</source>

Soweit ich das sehe wäre der richtige Pfad ohne "addons", also

<source>https://github.com/kodinerds/repo/tree/master/plugin.audio.radioteddy_de</source>

Zumindest sagt mein Kodi immer wenn ich euer Repo nutzen will, es könne nicht verbinden. Könnt Ihr das bitte mal überprüfen?

Gruss

**Comment by JinRonin** [comment]
Die Sources die dort angegeben werden, spielen in dem Fall keine Rolle.

ping @tyl0re 
Der Fehler kommt wohl von hier:
https://github.com/kodinerds/repo/commit/aa34dd0dcc91fb0ce621e80e6cd6ca6022a21014

**Comment by cspann** [comment]
Kann ich bestätigen. Danke @JinRonin fürs weiterleiten. Das Parsen der addons.xml schlägt fehl, da sie kein wohlgeformtes XML darstellt. Auszug aus der debug.log

```
22:30:25.766 T:140610585491200   DEBUG: CurlFile::Open(0x7fe273ffe950) https://raw.githubusercontent.com/kodinerds/repo/master/addons.xml
22:30:25.892 T:140610585491200   ERROR: CAddonMgr: Failed to parse addons.xml.
```

**Comment by nikostjafastgarnix** [comment]
genau dasselbe Problem kann ich auch bestätigen. Kann jemand helfen ?

**Comment by b-jesch** [comment]
Der Fehler ist bereits in der addon.xml des wakanim-Plugins enthalten. Ich bereinige mal die addon.xml und lass' den Parser nochmal rüberlaufen.

**Comment by nikostjafastgarnix** [comment]
\o/ - vielen Dank für die schnelle Abhilfe! läuft wieder !
