### ISSUE TITLE
[disneychannel.de] My Little Pony unresolvable URL

### ISSUE THREAD

**Issue by NeroBurner** [kodinerds/repo#51]
plugin: plugin.video.L0RE.disneychannel

The latest My Little Pony episode is not playing
Title: My Little Pony - Rarity in Mähnhattan

below the URLs that get resolved (with the code-snppets where the URLs are extracted)

from `def liste():` https://github.com/kodinerds/repo/blob/master/plugin.video.L0RE.disneychannel/default.py#L134
- `link=video["href"]`: http://tv.disney.de/sehen/my-little-pony-rarity-in-m-hnhattan-513d6bc03893cb62dd655a7a

from def playvideo(url): https://github.com/kodinerds/repo/blob/master/plugin.video.L0RE.disneychannel/default.py#L153
- `videourl=folge["embedURL"]`: https://secure.disney.com/embed/513d6bc03893cb62dd655a7a?domain=tv.disney.de
- `video=jsondata[-1]`: https://once-eu.unicornmedia.com/now/ctadaptive/m3u8/8965203b-457b-4352-b2e8-39143babaa47/e55f1475-f7d5-4e68-a8a0-a25273aa7fd0/6dc023aa-3041-4ec3-889a-3bd1838d5fc0/content.m3u8

the last URL cannot be resolved. All other videos play just fine

**Comment by tyl0re** [comment]
Can you look at the Hompage:
https://tv.disney.de/sehen/my-little-pony-rarity-in-m-hnhattan-513d6bc03893cb62dd655a7a

i just testet, it seems that the Video ist also working on their hompage. That would explain it.
Could you Verfiy it on your side

**Comment by NeroBurner** [comment]
Mähnhatten does not work on Android 8.1 (neither Firefox nor Chrome), or Ubuntu 16.04 (neither Firefox nor Chromium).

The Advertisement Video is shown, but then the video stays black and does never load the actual MLP video

I also tested the previous episode Flutterflughund ( http://tv.disney.de/sehen/my-little-pony-flutterflughund-513d6bbd50e44b62dd655a7a ), which does work.

**Comment by NeroBurner** [comment]
closing because old and not reproducible anymore. Most probably a error on disney's side
