### ISSUE TITLE
7TV  'DRM geschützte Folgen gehen nur mit Inputstream'

### ISSUE THREAD

**Issue by tiramon** [kodinerds/repo#53]
I just tried to look 'The Orville' on the 7TV app, but i always get  'DRM geschützte Folgen gehen nur mit Inputstream'

currently installed KODI 17.4 on a raspbery pi
7TV 0.5.24 

when i try it via my browser on my pc everything works fine

**Comment by tiramon** [comment]
Ok found that i have to activate the inputstream plugin
http://www.best-kodi-guides.eu/kodi-add-on-reviews/enable-inputstream-adaptive-kodi-krypton/

but now it shows a loading icon and then nothing happens ...

**Comment by Collabsvito** [comment]
Für DRM geschützte Folgen ist KODI-18 erforderlich !
