### ISSUE TITLE
dmax plugin 0.3.5 mixed indentation

### ISSUE THREAD

**Issue by Aydan** [kodinerds/repo#60]
plugin.video.LORE.dmax/default.py has tab indentation on lines 200 & 201.
```
strukturI = json.loads(contentI)
lickey=strukturI["keys"][0]["k"]        
```

**Comment by Ultrawipf** [comment]
It should be mentioned that the plugin is broken for 2 months now for all users. It crashes at startup due to the indentation error.

**Comment by Collabsvito** [comment]
Fixed !
