### ISSUE TITLE
Sky Ticket 1.0.9 Streaming problem

### ISSUE THREAD

**Issue by headstrong83** [kodinerds/repo#63]
15:23:15.679 T:1939120800   ERROR: Previous line repeats 6 times.
15:23:15.680 T:1939120800  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.skyticket.de/?action=playVod&parental_rating=12&vod_id=815231&infolabels=%7B%27plot%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27title%27%3A+u%27Das+Wort%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Die+Pest%27%2C+%27mediatype%27%3A+%27episode%27%2C+%27originaltitle%27%3A+%27%27%2C+%27cast%27%3A+%5B%5D%2C+%27duration%27%3A+3000%2C+%27genre%27%3A+%27%27%7D
15:23:15.680 T:1939120800   ERROR: CCurlFile::Stat - Failed: Unsupported protocol(1) for plugin://plugin.video.skyticket.de/?action=playVod&parental_rating=12&vod_id=815231&infolabels=%7B%27plot%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27title%27%3A+u%27Das+Wort%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Die+Pest%27%2C+%27mediatype%27%3A+%27episode%27%2C+%27originaltitle%27%3A+%27%27%2C+%27cast%27%3A+%5B%5D%2C+%27duration%27%3A+3000%2C+%27genre%27%3A+%27%27%7D
15:23:15.682 T:1509757808  NOTICE: Creating InputStream
15:23:18.498 T:1509757808   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 500
15:23:18.498 T:1509757808   ERROR: CCurlFile::Open failed with code 500 for https://wvguard.sky.de/WidevineLicenser/WidevineLicenser:
15:23:18.498 T:1509757808   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
15:23:18.498 T:1509757808   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
15:23:18.499 T:1509757808   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
15:23:18.500 T:1509757808   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.skyticket.de/?action=playVod&parental_rating=12&vod_id=815231&infolabels=%7B%27plot%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27title%27%3A+u%27Das+Wort%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Die+Pest%27%2C+%27mediatype%27%3A+%27episode%27%2C+%27originaltitle%27%3A+%27%27%2C+%27cast%27%3A+%5B%5D%2C+%27duration%27%3A+3000%2C+%27genre%27%3A+%27%27%7D]
15:23:18.501 T:1509757808  NOTICE: CVideoPlayer::OnExit()

**Comment by JinRonin** [comment]
Deine Geräteliste ist voll.
Mehr dazu hier: https://www.kodinerds.net/index.php/Thread/50836-beta-kodi-17-SkyGo-Plugin/?postID=478028#post478028

**Comment by headstrong83** [comment]
oh, ok. 
Danke
