### ISSUE TITLE
Netflix: pycryptodome version 3.4.3 could not be satisfied

### ISSUE THREAD

**Issue by the-blaggyS** [kodinerds/repo#64]
If I try to install Netflix I get the message: "The dependency on script.module.pycryptodome version 3.4.3. could not be satisfied."
I'am using LibreELEC with Kodi on Raspberry Pi.

**Comment by jasonlshelton** [comment]
I am also having this issue installing on kodi 17 on retropie on a pi3. I have installed pycryptomex using pip

I'm going to start poking around a bit and see what I can find, but if anyone else has some insight, I'd appreciate it.

**Comment by jasonlshelton** [comment]
Sorry, just found that this plugin doesn't work in kodi 17. will revisit this when I upgrade to 18,
