### ISSUE TITLE
sporttotal addon does not show volleyball games

### ISSUE THREAD

**Issue by benedetto** [kodinerds/repo#69]
Since this season, sportotal.tv does also stream the higher German Volleyball leagues. However, those cannot be accessed through the sporttotal addon. There are menu items for all the involved teams but they are empty. Also the matches are not listed in the "Live" section.

**Expected behaviour**: Currently running and near future matches are listed in the "Live" section. The menu in Volleyball/<League>/<Team name> does list matches of the respective team.

**Comment by Collabsvito** [comment]
@benedetto 
In the new release I have added "Alle Sportarten" from the website (incl. your wished sportarts).
Also in the section "LIVE Übertragungen" there are now Live-Games from other sportarts.

The addon would now have to be complete and contain all sections of the website.

HAVE FUN

**Comment by benedetto** [comment]
@Collabsvito Thanks a lot for the very quick fix! Couldn't check video streaming yet but the clubs and matches are displayed now! Works like a charm.
