### ISSUE TITLE
plugin.video.spotitube some Spotify playlists are empty

### ISSUE THREAD

**Issue by Rouzax** [kodinerds/repo#7]
When I open the plugin and open: `Spotify Playlists -> Toplists -> Top Tracks in The Netherlands` and `Today's Top Hits` it stays empty while `Top 100 tracks currently on Spotify` returns normal results.

**Comment by tyl0re** [comment]
Should be fixed in the Update today

**Comment by Rouzax** [comment]
Thank you very much :+1:
