### ISSUE TITLE
Sporttotal addon seems broken

### ISSUE THREAD

**Issue by benedetto** [kodinerds/repo#78]
Currenty, if I open the Sporttotal addon, I can see the top-level directory structure (LIVE-Übertragungen, Alle Portarten, Highlights, Top Clips, LIGEN, Archiv...) but if I enter one of those directories, I get an empty list with only the "back to the parent directory" two dots.

Is this happening only to me or do other users experience the same?

**Comment by Collabsvito** [comment]
@benedetto 

Fertiggestellt - viel Spaß damit ! :sunglasses: 

Gruß

**Comment by benedetto** [comment]
Das ging schnell. Danke und guten Rutsch.
