### ISSUE TITLE
Small request bc of planned API changes

### ISSUE THREAD

**Issue by phil65** [kodinerds/repo#8]
Hey guys,
one small request: Could you exchange .getdescription() method with .getLabel() at https://github.com/kodinerds/repo/blob/master/addons/service.subtitles.subcentral/default.py#L69 ? getdescription() is not thread-safe and we´d like to get rid of it in our API. We cannot afford to break existing scripts though, that´s  why I ask you to change it :) ( for info: .getLabel() returns exactly the same as .getdescription() )

**Comment by tyl0re** [comment]
Hi Changed it. Just have to find out how to make an PR Request for the Official Repo
