### ISSUE TITLE
plugin.video.sovietmoviesonline - categories and titles and Images

### ISSUE THREAD

**Issue by eX00r** [kodinerds/repo#87]
Thank you so much for this wonderful addon!

Unfortunately right now titles and categories show a <span>-tag as shown in the picture. That makes it somehow hard to read through. Maybe this is just a few lines of code. ;)

keep up the good work!

![plugin_video_sovietmoviesonline](https://user-images.githubusercontent.com/10723825/52259361-c0b19080-2922-11e9-9154-326be101cb21.jpg)

**Comment by Collabsvito** [comment]
@eX00r 

New Version 1.0.1 is online !
CHANGELOG:
- fixed: Listing of the Categories-Subfolders
- added: Categories = All-Movies, Movies by Decades and Movies by Directors
- added: Switch complete Addon-Language between "EN" and "RU"

TEST IT AND LIKE IT:smile:
